[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
oracle = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
prediction_market = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
afrifutures_bridge = "4kXhKyaVrRq2M1XmfwnhskKn32puw5xiE9jQPQ9RXvmK"

[programs.devnet]
oracle = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
prediction_market = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
afrifutures_bridge = "4kXhKyaVrRq2M1XmfwnhskKn32puw5xiE9jQPQ9RXvmK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = [
    "programs/oracle",
    "programs/prediction-market",
    "programs/wormhole-bridge"
]

[test]
startup_wait = 5000
